(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



1


Needs["JLink`"]


ReinstallJava[CommandLine -> "/Library/Java/Home/bin/java",JVMArguments->"-Xmx1000m -Xms1000m -Djava.library.path=/usr/local/lib/ -classpath \"/Work/library/clojure-1.2.0/clojure.jar:/Work/library/clojure-1.2.0/clojure-contrib-1.2.0.jar:/Applications/Mathematica.app/SystemFiles/Links/JLink/JLink.jar\""]


LoadJavaClass/@{"clojure.lang.Compiler","clojure.lang.RT","java.io.StringReader"}


load[str_]:=(
Compiler`load[JavaNew["java.io.StringReader",
str]])


load["(ns user) (defn part [a b] (.part a b))"]


load["(ns user) (defn head [a] (.head a))"];


load["(ns user) (defn length [a] (.length a))"];


load["(ns user) (use '[clojure.contrib.string :only [replace-str]]) (defn to-clojure-symbol [expr] 
				(let [sname (.asString expr)] 
					(cond 
						(= sname \"True\") true
						(= sname \"False\") false
						(= sname \"Null\") nil
						(= sname \"nil\") nil
						(= sname \"Equal\") '=
						(= sname \"SameQ\") '=
						(= sname \"Plus\") '+
						(= sname \"Times\") '*
						(= sname \"Division\") '/
						(= sname \"Rational\") '/
						(= sname \"Greater\") '>
						(= sname \"GreaterEqual\") '>=
						(= sname \"Less\") '<
						(= sname \"LessEqual\") '<=
						(= sname \"Unequal\") 'not=
						(= (subs sname 0 1) \"\[EmptyVerySmallSquare]\") (keyword (replace-str \"\[LongDash]\" \"_\" (replace-str \"\[Dash]\" \"-\" (subs sname 1 (count sname)))))
						true (symbol (replace-str \"\[LongDash]\" \"_\" (replace-str \"\[Dash]\" \"-\" (replace-str \"\[FilledVerySmallSquare]\" \".\" sname))))
					)
	))
"]


load["(ns user) (use '[clojure.contrib.string :only [replace-str]]) (defn to-s-expression [expr] 
	(let [conpart (fn [seq expr p] (conj seq (to-s-expression (part expr p))))] 
	(cond	
		(and (.atomQ expr) (not (.rationalQ expr))) 
			(cond 
				(.symbolQ expr) (to-clojure-symbol expr)
				(.integerQ expr) (.asInt expr)
				(.realQ expr) (.asDouble expr)
				(.stringQ expr) (.asString expr))
		(= (.asString (head expr)) \"List\") (reduce #(conpart %1 expr (+ %2 1)) [] (range (length expr)))
		(= (.asString (head expr)) \"HashMap\") (into {} (reduce #(conpart %1 expr (+ %2 1)) [] (range (length expr))))
		(= (.asString (head expr)) \"HashSet\") (into #{} (reduce #(conpart %1 expr (+ %2 1)) [] (range (length expr))))
		(= (.asString (head expr)) \"ClojureSymbol\") (symbol (.asString (part expr 1)))
		true (reverse (reduce #(conpart %1 expr (+ %2 1)) (conj '() (to-s-expression (head expr))) (range (length expr))))
	)))"]


load["(ns user) (defn evalm [expr] (binding [*ns* (create-ns 'user)] (eval expr)))"]


MakeClojureExpression[x_]:=ReturnAsJavaObject[(RT`var["user","to-s-expression"])@invoke[MakeJavaExpr@(x/. Times[a_,Power[b_,-1]]:>Division[a,b])]]


ClojureEvaluate[x_]/;JavaObjectQ[x]:=(RT`var["user","evalm"])@invoke[x]


ClojureEvaluate[x_]:=ClojureEvaluate[MakeClojureExpression[createExpr@x]]


load["(ns user) (use '[clojure.contrib.string :only [replace-str]]) (defn to-mathematica-symbol [expr] 
				(let [sname  (replace-str \"_\" \"\[LongDash]\" (replace-str \"-\" \"\[Dash]\" (replace-str \":\" \"\[EmptyVerySmallSquare]\" (replace-str \".\" \"\[FilledVerySmallSquare]\" (str expr)))))] 
					(cond
						(= sname \"+\") (com.wolfram.jlink.Expr. 4 \"Plus\") 
						(= sname \">\") (com.wolfram.jlink.Expr. 4 \"Greater\")
						(= sname \">=\") (com.wolfram.jlink.Expr. 4 \"GreaterEqual\")
						(= sname \"<\")  (com.wolfram.jlink.Expr. 4 \"Less\")
						(= sname \"<=\") (com.wolfram.jlink.Expr. 4 \"LessEqual\")
						(= sname \"=\") (com.wolfram.jlink.Expr. 4 \"Equal\")
						(= sname \"not=\") (com.wolfram.jlink.Expr. 4 \"Unequal\")
						(empty? (re-matches #\"(\\w|\[LongDash]|\[Dash]|\[FilledVerySmallSquare]|\[EmptyVerySmallSquare]|\\$)*\" sname)) (com.wolfram.jlink.Expr. (com.wolfram.jlink.Expr.  4 \"ClojureSymbol\") (into-array com.wolfram.jlink.Expr [(com.wolfram.jlink.Expr. sname)]))
						true (com.wolfram.jlink.Expr. 4 sname)
					)
	))
    
"]


load["(ns user)(use '[clojure.contrib.string :only [replace-str]]) (defn createExpr [struct] 
					(cond
						(= struct true) (com.wolfram.jlink.Expr. 4 \"True\")
						(= struct false) (com.wolfram.jlink.Expr. 4 \"False\")
						(= struct nil) (com.wolfram.jlink.Expr. 4 \"NotNull\")
						(ratio? struct) (com.wolfram.jlink.Expr. (com.wolfram.jlink.Expr.  4 \"Rational\") (into-array com.wolfram.jlink.Expr (map createExpr [(numerator struct) (denominator struct)])))
						(keyword? struct) (to-mathematica-symbol struct)
						(symbol? struct) (to-mathematica-symbol struct)
						(integer? struct) (com.wolfram.jlink.Expr.  1 (str struct))
						(float? struct) (com.wolfram.jlink.Expr.  2 (str struct))
						(string? struct) (com.wolfram.jlink.Expr. struct)
						(list? struct) (com.wolfram.jlink.Expr. (createExpr (first struct)) (into-array com.wolfram.jlink.Expr (map createExpr (rest struct))))
						(vector? struct) (com.wolfram.jlink.Expr. (com.wolfram.jlink.Expr.  4 \"List\") (into-array com.wolfram.jlink.Expr (map createExpr struct)))
						(map? struct) (com.wolfram.jlink.Expr. (com.wolfram.jlink.Expr.  4 \"HashMap\") (into-array com.wolfram.jlink.Expr (map createExpr struct)))
						(set? struct) (com.wolfram.jlink.Expr. (com.wolfram.jlink.Expr.  4 \"HashSet\") (into-array com.wolfram.jlink.Expr (map createExpr struct)))
						(seq? struct) (com.wolfram.jlink.Expr. (com.wolfram.jlink.Expr.  4 \"List\") (into-array com.wolfram.jlink.Expr (map createExpr struct)))
						true struct
					)	
		)"
]



